vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:

       avatar:
           uri_prefix: /images/avatar
           upload_destination: '%kernel.project_dir%/public/images/avatar'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       postThumbnail:
           uri_prefix: /images/posts
           upload_destination: '%kernel.project_dir%/public/images/posts'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer