version: '3'
 
services:
  db:
    image: mysql
    container_name: instapic_db
    environment:
      MYSQL_ROOT_PASSWORD: bleh
      MYSQL_DATABASE: pokedex
      MYSQL_USER: pokedex
      MYSQL_PASSWORD: 159pika
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myPhpAdmin
    links:
      - instapic_db
    environment:
      PMA_HOST: instapic_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 9000:80
    networks:
      - dev
      
  maildev:
    image: maildev/maildev
    container_name: instapic_devmail
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
      - "1025:25"
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  dbdata: